PAIR-code/what-if-tool

- WIT_Age_Regression.ipynb
- WIT_COMPAS.ipynb
- WIT_Model_Comparison.ipynb
- WIT_Toxicity_Text_Model_Comparison.ipynb
Updated all notebooks to work in tf2. All notebooks except text toxicity work in both tf1 and tf2.
Text toxicity only works in tf2, but includes ensuring tf2 is installed in its first cell. This is because its use of tf hub and keras models could not be done in a way to be compatible in both, and we want to show tf2 code moving forward.
> Update colabs to be tf2 compatible

- wit_dashboard/wit.html
- witwidget/notebook/colab/wit.py
- witwidget/notebook/jupyter/js/lib/wit.js
Add wit-dashboard invocation to wit_jupyter.html so that colab and jupyter implementations can remove use of the <link> HTML import, as this is removed in upcoming Chrome M80 and due to this, witwidget never worked in Firefox and similar browsers.
With this change, and a new pip version release, witwidget will work in Chrome M80 and Firefox/Safari.
> Remove <link> usage

- witwidget/notebook/colab/wit.py
- witwidget/notebook/jupyter/wit.py
Allows delayed rendering in colab and add explicit render method to render WitWidget outside of constructor. This includes a consistent rendering API between colab and jupyter, which was missing before.
This change also is 100% backwards compatible, not changing the behavior in either notebook environment if no code changes to notebooks are made.
> Add WitWidget delayed rendering option

- tensorboard_plugin_wit/pip_package/index.js
With this change, I was able to see grab the data in the URL by changing hash to `p.whatif.foo=bar` and using `await tb_plugin_lib.experimental.core.getURLPluginData()` in wit-tensorboard.html.
> Relay the plugin registration upwards.

- tensorboard_plugin_wit/pip_package/build_pip_package.sh
- wit_dashboard/wit-dashboard.html
- witwidget/pip_package/build_pip_package.sh
- witwidget/pip_package/setup.py
In order to have WIT be a dynamic TensorBoard plugin, it can't depend on tf-serving-api pip package, since that depends on TF which depends on TB.
The solution is the same one used by TensorBoard itself, which is to vendor the tf-serving-api python code into the WIT pip packages and point the WIT code that uses those files to the internally-vendored versions.
Tested this solution with the wit tensorboard pip package in a locally-built version of TB with the dynamic plugin, ensuring that the tf-serving-api package was not installed yet WIT was still able to correctly query and get responses from a model served by tf-serving.
Changes to build_pip_package.sh taken directly from TensorBoard versions of that file.
> Remove pip dependency on tf-serving-api

- tensorboard_plugin_wit/BUILD
- tensorboard_plugin_wit/pip_package/BUILD
- tensorboard_plugin_wit/pip_package/setup.py
- tensorboard_plugin_wit/wit_plugin_loader.py
The tensorboard-plugin-wit package as-is doesn't work with TensorBoard, because as part of their tests TensorBoard needs to be able to run (with limited capabilities) in environments without TensorFlow installed, but the WIT plugin requires TensorFlow installed.
This was solved with the non-dynamic-plugin WIT TensorBoard code through a TBPluginLoader (https://github.com/tensorflow/tensorboard/blob/9db185d058de97fa8b1f3ba151ad7c762d877540/tensorboard/plugins/interactive_inference/interactive_inference_plugin_loader.py).
This PR adds this same loader capability to the dynamic plugin.
Tested with TensorFlow installed in my local build and ensured it works as it did before this PR. 
Tested without TF installed through the TB CI process in https://github.com/tensorflow/tensorboard/pull/3242
> Add plugin loader for WIT TB plugin

- tensorboard_plugin_wit/wit_plugin.py
Hardcode encoding utf-8 for loading of JS/html files for WIT tensorboard plugin backend.
Tested internally.
> Fix WIT in TensorBoard running on machines with non-utf-8 default locale

- wit_dashboard/demo/wit-demo.html
- wit_dashboard/wit-dashboard.html
If a model from a model server returns class labels as string labels instead of class indices, WIT breaks. But in that case, if the user provides a label vocab, we can use it to map returned class labels to their indices, and un-break WIT in this case.
Updated:
- initial inference collection logic to handle classification by label from label vocab
- pd plot creation to handle inference results with label from label vocab
- one of the demos to return results in this format, for easy testing
> Allow models to return classification by label instead of index

- wit_dashboard/wit-dashboard.html
- wit_dashboard/wit-example-viewer.ts
If models return attributions, then allow counterfactual generation (and distance metric creation) based on attribution L1 and L2 distance, in addition to feature value L1 and L2 distance.
Also fixes issue where fully-unique numeric features were being ignored for distance calculations, including counterfactual generation.
> Add counterfactual generation by attributions

- tensorboard_plugin_wit/wit_plugin_loader.py
See https://github.com/tensorflow/tensorboard/issues/3460 for root cause.
This PR ensures that the tensorboard-plugin-wit package will only load the plugin in TensorBoards 2.2 or later, when WIT was removed as a built-in plugin.
> Do not load WIT TB plugin in TB versions earlier than 2.2

- WIT_Age_Regression.ipynb
- WIT_COMPAS.ipynb
- WIT_Model_Comparison.ipynb
- WIT_Smile_Detector.ipynb
- What_If_Tool_Notebook_Usage.ipynb
py2 colab kernel is deprecated and no longer works correctly with WIT.
> Move colabs to py3 kernels

- utils/inference_utils.py
This PR fixes an error when creating sprite for image data due to data type mismatch.
tf.image.encode_png only accepts uint8 or uint16, whereas we were passing float. Something may have changed in TF1->TF2 update that removed auto type conversion as this code used to work before.
Tested smile demo in colab to verify the fix works.
> Fix type error for sprite generation for images

- DEVELOPMENT.md
Adding a note on speeding up local development, from https://github.com/PAIR-code/what-if-tool/issues/89.
> Docs: Add note about changing Closure compiler level locally

- wit_dashboard/wit-attribution-table.html
- wit_dashboard/wit-dashboard.html
- wit_dashboard/wit-example-viewer.ts
Updates all per discussions with Mahima for UX:
- Use existing attributions color scale in global attributions table
- Left-align all performance indicators in performance table, instead of center-align
- Add info button/popup to global attributions table
- Remove gutter from expanded performance row in table
- Some border/spacing fixes in performance tables
- Styling global attributions table per feedback
For issue #81
> Update global attributions table styling

- wit_dashboard/wit-dashboard.html
This change adds AUCs for each series to the title of precision-recall charts (see https://github.com/PAIR-code/what-if-tool/issues/78), like these examples:
<div>
</div>
To do this, it adds a new property, `aucs_`.  When `plotChart` is called for a precision-recall chart, it computes the AUC and stores in `aucs_` keyed on `(chartId, modelIndex)`.  The charts in templates then call different methods to get the text for their titles.  Using the `[[getWhatever(foo, bar))]]` approach in the template works in practice to push changes back to the DOM, but only when setting the entire `this.aucs_` property at once.  I fiddled with `this.set('aucs_.${key}')` and `observers` and `{{bindings}}` but this approached seemed similar to what's used in other places and I it had the benefit of working :) …
> Performance tab: Add AUC for precision-recall charts

- README.md
- tensorboard_plugin_wit/wit_plugin.py
- tensorboard_plugin_wit/wit_plugin_loader.py
- utils/inference_utils.py
This PR enables What-If-Tool to load the custom_predict_fn when running in a local TensorBoard server. The modification tries to load a python function `custom_predict_fn` from a file named `custom_wit_predict_fn.py` in TensorBoard's launching folder. If the function exists, the inference request will be redirected to that function. 
Tested locally with a compiled python wheel file along with the demo code in
https://github.com/pytorch/serve/pull/418
> Add support for custom predict function in non-colab environment

- witwidget/pip_package/setup.py
tf.get_logger() is exposed starting from 1.12.1. 
If you use WitWidget with tensorflow 1.12.0 you get the following error:
```
witwidget\notebook\base.py in __init__(self, config_builder)
50       config_builder: WitConfigBuilder object containing settings for WIT.
51     """
52     tf.get_logger().setLevel(logging.WARNING)
53     config = config_builder.build()
54     copied_config = dict(config)
AttributeError: module 'tensorflow' has no attribute 'get_logger'
> Bump tensorflow requirement from 1.12.0 to 1.12.1

- DEVELOPMENT.md
- README.md
- tensorboard_plugin_wit/pip_package/build_pip_package.sh
- tensorboard_plugin_wit/wit_plugin.py
- witwidget/pip_package/build_pip_package.sh
- witwidget/pip_package/setup.py
Updating documentation for upcoming launch
Removing py2 and tensorflow-gpu versions of pip packages. Py2 support is gone in 2020 and tensorflow-gpu has been deprecated.
Small fixes from last PR on custom predict functions in TensorBoard.
> Clean up for next launch

- tensorboard_plugin_wit/wit_plugin_loader.py
Summary:
When the `except argparse.ArgumentError` case is hit, the code throws
anyway because the `argparse` identifier is not bound.
Test Plan:
Running `flake8 --select=F82` to check for name binding violations now
reports the whole repository as clean; previously, it caught this error.
wchargin-branch: import-argparse
> loader: import `argparse`

- tensorboard_plugin_wit/wit_plugin.py
- wit_dashboard/wit-dashboard.html
- Change error responses from server to be just strings
- Catch all error types in server error catching logic
- Change failed request display logic in front-end to display the internal error text, and not just a generic 400 error message
What errors look like with this change:
> Display actual server error text in tool

- witwidget/notebook/jupyter/js/lib/index.js
- witwidget/notebook/jupyter/js/lib/wit.js
- witwidget/notebook/jupyter/js/package.json
To fix #71
Removed unnecessary use of file-loader, which had issues with ES6 and JupyterLab 2
Simplified __nbextension_path__ setting/logic
Updated wit-widget package.json to support all JupyterLab versions and remove conflicting and unnecessary dep on jupyterlab-manager (TFMA package, which works the same way, doesn't have this dependency, for example).
> Enable WitWidget in JupyterLab2

- tensorboard_plugin_wit/wit_plugin.py
- wit_dashboard/wit-dashboard.html
The logic to pass extra outputs (including attributions) back from py to javascript was missing from the TensorBoard implementation. Added it in, following the same chunking logic as already existed for inference values and for extra outputs in notebook modes.
Tested locally with custom predict fns in TB: one with attributions, one just with predictions. Tested with small datasets and datasets over 10k in size, to test chunking. Tested with one model and also with two models.
Fixes #152
> Handle attributions in custom predict functions in TensorBoard

- tensorboard_plugin_wit/pip_package/build_pip_package.sh
- witwidget/pip_package/build_pip_package.sh
Related to #34, #35
It seems that `build_pip_package.sh` requires `pushd`, which is unknown in `sh` and prevented me from building. 
This commit allows me to build the package. If there is no good reason to use `/bin/sh`, I propose to explicitly require `/bin/bash`. Otherwise, I do not see a good way to build the package on a system without root access and default shell `sh`. 
Let me know what you think!
> Change /bin/sh to /bin/bash in build_pip_package.sh

- tensorboard_plugin_wit/pip_package/setup.py
- wit_dashboard/wit-dashboard.html
TensorBoard can be launched with a `--path_prefix=[path]` option to set a path prefix in the URL of tensorboard (useful when running in certain environments such as notebooks). WIT was using a hard-coded absolute path for its calls to the TensorBoard WIT backend, which would fail when TB was launched with a path_prefix.
This fix updates the WIT backend calls (these are only done when WIT is being used inside TensorBoard) to be relative paths, so the path_prefix is correctly used by the TensorBoard request manager. This fix also uses TB's addParams method universally instead of adding query params by hand.
Tested this fix both with a standard TB instance and one with a path_prefix set and ensured that WIT works correctly in both situations now.
Fixes #190 and …
> Fix WIT backend calls when TensorBoard uses path_prefix option
